### PR TITLE
set up renv in this project

### PR DESCRIPTION
**Pull request by egnor**
I don't know what you think about [renv](https://rstudio.github.io/renv/articles/renv.html) but I find it absolutely invaluable for library development, to avoid depending on a global R environment and its unpredictable contents.

(If you're not into it, then I'll just use it locally! Maybe you'd let me at least add its files to `.gitignore` in that case.)

### CODE REVIEW

**Comment by egnor** [comment]
Added a reference to `bunny` (and improved the `.Rprofile` logic to be more robust) to fix
https://github.com/EduSemensati/sentryR/issues/28

**Comment by jcpsantiago** [comment]
I use it on all my projects actually, but usually skip it for libraries. I don't see any problems with adding it. Thanks!

I'm waiting for this repo to be transfered to my personal account, I'll merge this as soon as that happens (ETA today or tomorrow)

**Comment by egnor** [comment]
Also I should figure out what's up with the CI failures!

**Comment by egnor** [comment]
CI failures --

MacOS: This looks unrelated to this change?? Maybe related to the old `setup-r@v1` action?
image

Ubuntu (both versions): This is definitely related to this change, strange how it's not able to use the `Remotes:`? Looking into that.
image

**Comment by egnor** [comment]
Running `rcmdcheck` in my local environment works fine:

image

Again, maybe an issue with the older versions of the R workflow actions?

**Pull request merged**
